project_name: type_C
model:
  name: resnet50
  num_classes: 10
  pretrained: true
data:
  root_dir: ./data/type_C
  input_size: 224
  batch_size: 32
  num_workers: 0
train:
  learning_rate: 0.001
  epochs: 20
  seed_size: 250
active_learning:
  query_size: 100
  strategy: entropy
